///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ReadFromScreeen
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the BisAutotestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    [RepositoryFolder("f72f759f-1375-4c44-934f-5eff674030f8")]
    public partial class BisAutotestRepository : RepoGenBaseFolder
    {
        static BisAutotestRepository instance = new BisAutotestRepository();
        BisAutotestRepositoryFolders.AnyPuTTYAppFolder _anyputty;
        BisAutotestRepositoryFolders.PuttyAppFolder _putty;

        /// <summary>
        /// Gets the singleton class instance representing the BisAutotestRepository element repository.
        /// </summary>
        [RepositoryFolder("f72f759f-1375-4c44-934f-5eff674030f8")]
        public static BisAutotestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public BisAutotestRepository() 
            : base("BisAutotestRepository", "/", null, 0, false, "f72f759f-1375-4c44-934f-5eff674030f8", ".\\RepositoryImages\\BisAutotestRepositoryf72f759f.rximgres")
        {
            _anyputty = new BisAutotestRepositoryFolders.AnyPuTTYAppFolder(this);
            _putty = new BisAutotestRepositoryFolders.PuttyAppFolder(this);
        }

#region Variables

        string _textFromScreen = "";

        /// <summary>
        /// Gets or sets the value of variable textFromScreen.
        /// </summary>
        [TestVariable("471e7ab7-8efc-4c28-bd9e-0474129a4ee8")]
        public string textFromScreen
        {
            get { return _textFromScreen; }
            set { _textFromScreen = value; }
        }

        string _textFromScreen2 = "Hi!";

        /// <summary>
        /// Gets or sets the value of variable textFromScreen2.
        /// </summary>
        [TestVariable("5c97d17f-f862-4e1d-9d3f-223d4b8c0633")]
        public string textFromScreen2
        {
            get { return _textFromScreen2; }
            set { _textFromScreen2 = value; }
        }

        string _controlVar = "1";

        /// <summary>
        /// Gets or sets the value of variable controlVar.
        /// </summary>
        [TestVariable("f59bd2f6-97de-437f-a2da-ba5460109bfe")]
        public string controlVar
        {
            get { return _controlVar; }
            set { _controlVar = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f72f759f-1375-4c44-934f-5eff674030f8")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The AnyPuTTY folder.
        /// </summary>
        [RepositoryFolder("0cd17e81-ae9f-46b2-975b-d814adc2da59")]
        public virtual BisAutotestRepositoryFolders.AnyPuTTYAppFolder AnyPuTTY
        {
            get { return _anyputty; }
        }

        /// <summary>
        /// The Putty folder.
        /// </summary>
        [RepositoryFolder("df00f1ea-0146-4071-bfad-7d5484101839")]
        public virtual BisAutotestRepositoryFolders.PuttyAppFolder Putty
        {
            get { return _putty; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    public partial class BisAutotestRepositoryFolders
    {
        /// <summary>
        /// The AnyPuTTYAppFolder folder.
        /// </summary>
        [RepositoryFolder("0cd17e81-ae9f-46b2-975b-d814adc2da59")]
        public partial class AnyPuTTYAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _anyputtyInfo;
            RepoItemInfo _системаInfo;

            /// <summary>
            /// Creates a new AnyPuTTY  folder.
            /// </summary>
            public AnyPuTTYAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AnyPuTTY", "/form[@title='ibm.bis.corp - PuTTY']", parentFolder, 3000, null, true, "0cd17e81-ae9f-46b2-975b-d814adc2da59", "")
            {
                _anyputtyInfo = new RepoItemInfo(this, "AnyPuTTY", "titlebar[@accessiblerole='TitleBar']", 3000, true, "8b08f20c-6cfd-4205-adbd-cde3918aa039");
                _системаInfo = new RepoItemInfo(this, "Система", "?/?/menuitem[@accessiblename='Система']", 3000, true, "8a550282-a6d4-40fe-a45e-2f96db0622ee");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0cd17e81-ae9f-46b2-975b-d814adc2da59")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0cd17e81-ae9f-46b2-975b-d814adc2da59")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AnyPuTTY item.
            /// </summary>
            [RepositoryItem("8b08f20c-6cfd-4205-adbd-cde3918aa039")]
            public virtual Ranorex.TitleBar AnyPuTTY
            {
                get
                {
                    return _anyputtyInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The AnyPuTTY item info.
            /// </summary>
            [RepositoryItemInfo("8b08f20c-6cfd-4205-adbd-cde3918aa039")]
            public virtual RepoItemInfo AnyPuTTYInfo
            {
                get
                {
                    return _anyputtyInfo;
                }
            }

            /// <summary>
            /// The Система item.
            /// </summary>
            [RepositoryItem("8a550282-a6d4-40fe-a45e-2f96db0622ee")]
            public virtual Ranorex.MenuItem Система
            {
                get
                {
                    return _системаInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Система item info.
            /// </summary>
            [RepositoryItemInfo("8a550282-a6d4-40fe-a45e-2f96db0622ee")]
            public virtual RepoItemInfo СистемаInfo
            {
                get
                {
                    return _системаInfo;
                }
            }
        }

        /// <summary>
        /// The PuttyAppFolder folder.
        /// </summary>
        [RepositoryFolder("df00f1ea-0146-4071-bfad-7d5484101839")]
        public partial class PuttyAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _copyalltoclipboardInfo;

            /// <summary>
            /// Creates a new Putty  folder.
            /// </summary>
            public PuttyAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Putty", "/contextmenu[@processname='putty']", parentFolder, 3000, null, true, "df00f1ea-0146-4071-bfad-7d5484101839", "")
            {
                _copyalltoclipboardInfo = new RepoItemInfo(this, "CopyAllToClipboard", "?/?/menuitem[@accessiblename='Copy All to Clipboard']", 3000, true, "33820e4c-bf4c-45f2-8b3e-cd9883637ff6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("df00f1ea-0146-4071-bfad-7d5484101839")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("df00f1ea-0146-4071-bfad-7d5484101839")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CopyAllToClipboard item.
            /// </summary>
            [RepositoryItem("33820e4c-bf4c-45f2-8b3e-cd9883637ff6")]
            public virtual Ranorex.MenuItem CopyAllToClipboard
            {
                get
                {
                    return _copyalltoclipboardInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The CopyAllToClipboard item info.
            /// </summary>
            [RepositoryItemInfo("33820e4c-bf4c-45f2-8b3e-cd9883637ff6")]
            public virtual RepoItemInfo CopyAllToClipboardInfo
            {
                get
                {
                    return _copyalltoclipboardInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}